######### Registro do Usuário
POST https://tuiobend.onrender.com/register HTTP/1.1
Content-Type: application/json

{
    "name": "Túlio",
    "email": "tuliovrcpa2015@gmail.com",
    "password": "1234"
}

######### Autenticação do usuário
POST https://tuiobend.onrender.com/login HTTP/1.1
Content-Type: application/json

{
    "email": "tuliovrcpa2015@gmail.com",
    "password": "1234"
}




