######### Registro do Usuário
POST http://127.0.0.1:3333/register HTTP/1.1
Content-Type: application/json

{
    "name": "Túlio",
    "email": "tuliovrcpa2015@gmail.com",
    "password": "1234"
}

######### Autenticação do usuário
POST http://127.0.0.1:3333/register HTTP/1.1
Content-Type: application/json

{
    "email": "tuliovrcpa2015@gmail.com",
    "password": "1234"
}




